### ISSUE TITLE
no opencv_java310

### ISSUE THREAD

**Issue by zhanybekovv** [cansik/architectural-floor-plan#49]
Hello,
I'm having trouble with running your software. I'm getting the error Caused by: java.lang.UnsatisfiedLinkError: no opencv_java310 in java.library.path, how can I improve it. I tries to run on windows and ubuntu 18.02, nothing changed. If you help me that would be great!
Sincerely, 
Nartay Zhanybekov

**Comment by cansik** [comment]
Did you use the run.bat or just double clicked the jar?
