### ISSUE TITLE
Link to documentation is broken!

### ISSUE THREAD

**Issue by imankareem** [cansik/architectural-floor-plan#50]
Hey Florian,

**Your work in this project is amazing**, _I am just not sure how to use it!_

The link to the documentation doesn't work - https://github.com/cansik/architectural-floor-plan/releases/download/v1.0/AASAFP_BruggisserWyss_2017.pdf 

Could you please update the link?

Thank you!

**Comment by redcpp** [comment]
I think they were deleted on purpose as seen in commit 91acc5f1d9658352aae27aeb379c245d48ce9a96

**Comment by cansik** [comment]
@redcpp Yes, the "documentation" has been removed, because it was the full bachelor thesis and not just a paper about it. Maybe I find time to sum it up into a short documentation. I removed the link to it.

**Comment by preethamam** [comment]
@cansik, 

Could you please share the thesis?
