### ISSUE TITLE
Error: Could not find or load main class ch.fhnw.afpars.Main

### ISSUE THREAD

**Issue by redcpp** [cansik/architectural-floor-plan#51]
Hi,
Your tool sounds like a really cool project and I'd like to try it out but can't.
Just cloned it but this is the error I'm getting when running **run.sh**.

```bash
➜  1.0 git:(master): sh run.sh
Error: Could not find or load main class ch.fhnw.afpars.Main
```

I'm using Java 8
```bash
➜ java -version
openjdk version "1.8.0_232"
OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_232-b09)
OpenJDK 64-Bit Server VM (AdoptOpenJDK)(build 25.232-b09, mixed mode)
```

It's also failing when building with gradle
```bash
➜  afpars git:(master): gradle build --warning-mode=all

FAILURE: Build failed with an exception.

* Where:
Build file '/Users/jakobandersen/Documents/inmuebles/AFPlan/afpars/build.gradle' line: 15

* What went wrong:
A problem occurred evaluating root project 'Afpars'.
> Could not initialize class org.jetbrains.kotlin.gradle.internal.KotlinSourceSetProviderImplKt
```

Thank you very much for your help.

**Comment by cansik** [comment]
I am currently having trouble running it too, but more because of Mac Catalina telling me that the opencv binary is not signed.

Have you tried running it with OracleJDK instead of an OpenJDK build?

**Comment by redcpp** [comment]
Uninstalling OpenJDK and installing OracleJDK did the trick. Thank you!
