### ISSUE TITLE
Error: Could not find or load main class ch.fhnw.afpars.Main

### ISSUE THREAD

**Issue by anthonymakela** [cansik/architectural-floor-plan#52]
There seems to be an error while trying to run `run.sh` on Ubuntu. What might be causing this?

Java version:

> openjdk version "1.8.0_242"
OpenJDK Runtime Environment (build 1.8.0_242-8u242-b08-0ubuntu3~18.04-b08)
OpenJDK 64-Bit Server VM (build 25.242-b08, mixed mode)

**Comment by cansik** [comment]
OpenJDK is not supported as already mentioned in https://github.com/cansik/architectural-floor-plan/issues/51.

**Comment by anthonymakela** [comment]
OracleJDK build seems to be giving the same error? 

`Error: Could not find or load main class ch.fhnw.afpars.Main
Caused by: java.lang.ClassNotFoundException: ch.fhnw.afpars.Mainor`

> java version "11.0.6" 2020-01-14 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.6+8-LTS)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.6+8-LTS, mixed mode)

**Comment by cansik** [comment]
It's a Java 8 project, never tried to run it on Java 11 but in my opinion it won't work because of JavaFX. The project is already quite old and is not maintained since then.

**Comment by anthonymakela** [comment]
Hmm, this still keeps popping up... Could it be some dependency issue?

`Error: Could not find or load main class ch.fhnw.afpars.Main`


> java version "1.8.0_241"
Java(TM) SE Runtime Environment (build 1.8.0_241-b07)
Java HotSpot(TM) 64-Bit Server VM (build 25.241-b07, mixed mode)

**Comment by anthonymakela** [comment]
Any updates on this? @cansik

**Comment by GenieTim** [comment]
I got it working on Java 11, versions: Kotlin SDK 1.3.61, language level 13, JDK 11.0.4, OpenJFX 11.0.2.
The compilation is different. The relevant change is that since JavaFX does not come bundled, it has to be [downloaded](https://openjfx.io/index.html) and added to the classpath separately. @anthonymakela you probably have to compile it yourself. I can provide you with my IntelliJ setup (which do work, the program runs) if that helps.

**Comment by cansik** [comment]
I have updated the project to support JDK 11 (also OpenJDK) and higher. Just build & run it with the following command:

```bash
cd afpars
./gradlew run
```
