### ISSUE TITLE
CSV bug

### ISSUE THREAD

**Issue by Ramanpreet1992** [cansik/architectural-floor-plan#54]
The CSV is not having the Locations of the rooms. as mentioned in the readme. The CSV is having the room id, size, and pixels. Kindly help or guide to fix the bug.
![2020-07-16 (3)](https://user-images.githubusercontent.com/56839995/87703314-02c63f00-c771-11ea-88ee-e77aaab74ae6.png)

**Comment by cansik** [comment]
What would be "**the location**" for you? All the polygon vertices or just the center point? I guess we did not implement that into the CSV, because there is no fixed answer for that. If you tell me what kind of location you are looking for, I can guide you in the right direction.

**Comment by Ramanpreet1992** [comment]
I assume for me the location will be defined as the x and y coordinates of the vertices so that I can map the polygons from the SVG with the data already there in the CSV.
I wish to connect SVG and CSV and find the area of each polygon.

**Comment by cansik** [comment]
I have implemented a simple solution for this, check out this line which adds all the vertices: [MainView.kt#L412](https://github.com/cansik/architectural-floor-plan/blob/master/afpars/src/main/kotlin/ch/fhnw/afpars/ui/controller/MainView.kt#L412)

Be aware that I have updated the project to support Java11, so please upgrade your toolchain.

**Comment by Ramanpreet1992** [comment]
Can we run the tool in CLI mode. I wish to load the image, run all the analysis and finally save the data in the csv format and svg format.

**Comment by Ramanpreet1992** [comment]
I could not regenerate the map out of the x and y coordinates from the CSV file. I intend to regenerate the floor plan from the CSV alone so that I can check which room has what area. Could you please help with this.

**Comment by cansik** [comment]
Please show me what you are trying to do, what does not work and how I can reproduce it.

**Comment by Ramanpreet1992** [comment]
We have collaborated the information through python. Thanks for helping to resolve this issue.
