### ISSUE TITLE
Java Runtime Issue

### ISSUE THREAD

**Issue by mjgaughan** [cansik/architectural-floor-plan#55]
While trying to build the app with "./gradlew run", I keep running into an issue with my Java runtime. Not sure if this is specific to this project but still getting the issue even after updating Java to the most recent version. My peer is also running into the same issue and is unsure of how to fix it. Any ideas?

**Comment by cansik** [comment]
Without any knowledge about your java runtime its impossible to help you. Please provide your java virtual machine version, and operating system.

**Comment by mjgaughan** [comment]
My apologies for the lack of information. I'm using macOS 10.14.6—wasn't using a VM... I've attached a screenshot of my error below. 
<img width="1417" alt="Screen Shot 2020-08-16 at 4 35 14 PM" src="https://user-images.githubusercontent.com/58380965/90346593-1fa79980-dfdf-11ea-895c-f77b03ba4dc4.png">

**Comment by cansik** [comment]
Your Java version supports class files up to `52.0`, in this project `55.0` is used. If you google that, you quickly find out, that you are using **Java 8**, but this project states in the [readme](https://github.com/cansik/architectural-floor-plan#development-prerequisites), that **Java 11** or higher is required.

Next time, please do a bit of research on your own and at least google the error message once before posting an issue. Taking care of issues is time intensive, so you should first validate that it is a project related bug and not something within your setup.
